### ISSUE TITLE
Невозможно обращение к роутеру (OpenVpn клиент) из сети сервера

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wl500g/wl500g#451]
```
What steps will reproduce the problem?
Настроить OpenVpn тунель между 2-мя сетями, в 
результате нет возможности обратиться к 
роутеру-клиенту из сети сервера.
подробности 
http://wl500g.info/showthread.php?30109-%D3%F1%F2%E0%ED%EE%E2%EA%E0-%E8-%ED%E0%F
1%F2%F0%EE%E9%EA%E0-VPN-OpenVPN-%F7%E5%F0%E5%E7-3G-4G-(Yota)-%EC%EE%E4%E5%EC&p=2
66244#post266244

На версии 5066 - работает, 5450 и 5566 -нет

Отключение FastNat не помогает. 

```

Original issue reported on code.google.com by `Mike.Sem...@gmail.com` on 7 Sep 2014 at 4:36

**Comment by mikeS7** [comment]
На прошивке WL500W-1.9.2.7-rtn-r7226M-g691b2b9.trx уходит в перезагрузку, причем модем Skylink виснет

**Comment by lly-dev** [comment]
Какое отношение этот факт имеет к OpenVPN?
Для диагностики этой информации недостаточно.

**Comment by mikeS7** [comment]
Добавляю, на прошивке WL500W-1.9.2.7-rtn-r7226M-g691b2b9.trx при обращении к рутеру (клиенту OpenVpn) из сети сервера, рутер клиент перезагружается
Откатился на 7096.

**Comment by lly-dev** [comment]
Если нет возможности получить текст kernel Oops, просьба проверить другие билды - 7190, 7202

**Comment by mikeS7** [comment]
Рутер стоит на даче, проверю в следующие выходные.

**Comment by lly-dev** [comment]
Просьба не забывать, что модули ядра в /opt/lib/modules должны соответствовать билду.

**Comment by themiron** [comment]
вероятно r7396 поможет, см. http://asus.vectormm.net/rtn/

**Comment by mikeS7** [comment]
проверил на r7438, не помогает
больше не актуально, заменил рутер

**Comment by Snegohod** [comment]
@themiron такая же проблема на r7470.
В чем может быть проблема?

**Comment by dvglab** [comment]
Проблема пришла с коммитом d2195cd85cfc73b90a796911288846098f4126e3
до него все работает, после него нет, в этом коммите пришли патчи с апстрима, которые и сломали правильную работу tun.c

**Comment by Snegohod** [comment]
@dvglab можешь собрать последнюю версию прошивки с правильным tun.c?

**Comment by dvglab** [comment]
В моей системе сборки не все пакеты собираются, завтра буду пробовать собрать еще раз, но на сегодня например не собирается самба. Я просто отключил ее т.к. мне она не нужна. Если получится выложу ссылку.

**Comment by Snegohod** [comment]
@dvglab как успехи?
Можешь выложить без samba, я ее тоже не использую.
Заранее спасибо.

**Comment by dvglab** [comment]
Собрал без самбы и snmp агента, он у меня тоже не собирается. Версия с правильным tun.c но без этих двух пакетов лежит тут [https://drive.google.com/folderview?id=0B3siHuUeUYRBbk5CUXdwZmJLV0E&usp=sharing](url)

**Comment by tollys69** [comment]
Добрый день

У меня та же проблема. Роутеры RT-N16, WL500gpv2
Проверял на версиях 7440, 7487

**Comment by dvglab** [comment]
собрал наконец все пакеты, по линку выше можно скачать версии для RT-N16,RT-N12,RT-N15U,RT-N10

**Comment by themiron** [comment]
fixed with commit d251010
