### ISSUE TITLE
Dnsmasq reload many times

### ISSUE THREAD

**Issue by AlexeySa** [wl500g/wl500g#475]
Router ASUS WL500GP v1. Firmware 1.9.2.7-rtn-r7393M-g9e2e514. Provider Onlime.

I found in the logs messages from dnsmasq. These messages are repeated every 15 min. I do not know how to fix it. Problem appeared after switch on IPv6 settings.

I noticed:
1) Messages are similar to those caused by a reload command `killall -HUP dnsmasq`
2) Messages stoped after `killall dhcp6c`

Log cat:
>Feb 20 07:53:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 07:53:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 07:53:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 07:53:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 07:53:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 07:53:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 07:53:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 07:53:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 07:53:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 07:53:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 07:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 07:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:08:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:08:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:08:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:08:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:08:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:08:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:08:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:08:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:08:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:08:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:23:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:23:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:23:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:23:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:23:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:23:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:23:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:23:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:23:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:23:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:38:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:38:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:38:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:38:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:38:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:38:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:38:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:38:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:38:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:38:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:53:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:53:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:53:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:53:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:53:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:53:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 08:53:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 08:53:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 08:53:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 08:53:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 08:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 08:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:08:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:08:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:08:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:08:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:08:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:08:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:08:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:08:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:08:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:08:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:23:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:23:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:23:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:23:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:23:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:23:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:23:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:23:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:23:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:23:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:38:28 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:38:28 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:38:28 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:38:28 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:38:28 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:38:28 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:38:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:38:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:38:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:38:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:53:29 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:53:29 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:53:29 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:53:29 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:53:29 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:53:29 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:53:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 09:53:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 09:53:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 09:53:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 09:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 09:53:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 09:59:37 dnsmasq-dhcp[237]: DHCPREQUEST(br0) 192.168.100.10 f0:7d:68:af:0d:ef 
Feb 20 09:59:37 dnsmasq-dhcp[237]: DHCPACK(br0) 192.168.100.10 f0:7d:68:af:0d:ef Lilicomp
Feb 20 10:08:29 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:08:29 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:08:29 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:08:29 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:08:29 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:08:29 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 10:08:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:08:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:08:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:08:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:08:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 10:23:29 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:23:29 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:23:29 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:23:29 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:23:29 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:23:29 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 10:23:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:23:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:23:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:23:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:23:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 10:38:29 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:38:29 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:38:29 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:38:29 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:38:29 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:38:29 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53
Feb 20 10:38:38 dnsmasq[237]: read /etc/hosts - 10 addresses
Feb 20 10:38:38 dnsmasq-dhcp[237]: read /etc/ethers - 11 addresses
Feb 20 10:38:38 dnsmasq[237]: using nameserver 77.37.251.33#53
Feb 20 10:38:38 dnsmasq[237]: using nameserver 77.37.255.30#53
Feb 20 10:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:1::1#53
Feb 20 10:38:38 dnsmasq[237]: using nameserver 2a02:2168:208:2::1#53

**Comment by themiron** [comment]
the reason - your ISP uses 900s lifetime for DNS records
