### ISSUE TITLE
Fix screenshot on wiki page

### ISSUE THREAD

**Issue by maxbanton** [wl500g/wl500g#488]
Hi!
Looks like link to the screenshot image file in broken on [this wiki page](https://github.com/wl500g/wl500g/wiki/GUIIPConfigIPv6HowTo6in4) line 105.
Please, fix it by replacing with `https://raw.githubusercontent.com/wiki/wl500g/wl500g/GUIIPConfigIPv6HowTo6in4.png` link.

In addition, may be it's good idea to make wiki of this repo public editable to allow contributions to the documentation from community?

**Comment by themiron** [comment]
Hi, 

Thanks a lot, fixed.
As for public access, we’ll discuss it.

 

Best Regards, Vladislav Grishenko
